# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='image', verbose_name='image')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
